import { Icon } from '@mdi/react';
import {
    mdiTrophy,
    mdiTrophyAward,
    mdiTrophyVariant,
    mdiMedal,
    mdiMedalOutline,
    mdiCrown,
    mdiCrownOutline,
    mdiStar,
    mdiStarOutline,
    mdiStarFourPoints,
    mdiStarThreePoints,
    mdiStarCircle,
    mdiStarFace,
    mdiEmoticonHappy,
    mdiEmoticonCool,
    mdiEmoticonDevil,
    mdiEmoticonExcited,
    mdiFire,
    mdiLightningBolt,
    mdiLightningBoltCircle,
    mdiShield,
    mdiShieldOutline,
    mdiShieldCheck,
    mdiShieldCheckOutline,
    mdiShieldAlert,
    mdiShieldAlertOutline,
    mdiShieldStar,
    mdiShieldStarOutline,
    mdiShieldLock,
    mdiShieldLockOutline,
    mdiSword,
    mdiSwordCross,
    mdiAxe,
    mdiAxeBattle,
    mdiMace,
    mdiHammer,
    mdiHammerScrewdriver,
    mdiHammerWrench,
    mdiWrench,
    mdiWrenchClock,
    mdiCog,
    mdiCogOutline,
    mdiCogPlay,
    mdiCogPlayOutline,
    mdiCogBox,
    mdiTools,
    mdiScrewdriver,
    mdiPliers,
    mdiPencil,
    mdiPencilOutline,
    mdiPencilRuler,
    mdiPen,
    mdiBrush,
    mdiPalette,
    mdiPaletteOutline,
    mdiFormatPaint,
    mdiCodeBraces,
    mdiCodeBracesBox,
    mdiCodeTags,
    mdiConsole,
    mdiMonitor,
    mdiMonitorCellphone,
    mdiLaptop,
    mdiCellphone,
    mdiTablet,
    mdiServer,
    mdiDatabase,
    mdiDatabaseOutline,
    mdiHarddisk,
    mdiMemory,
    mdiChip,
    mdiCpu64Bit,
    mdiCpu32Bit,
    mdiVideo,
    mdiVideoOutline,
    mdiCamera,
    mdiCameraOutline,
    mdiImage,
    mdiImageOutline,
    mdiFile,
    mdiFileOutline,
    mdiFileDocument,
    mdiFileDocumentOutline,
    mdiFileCode,
    mdiFileCodeOutline,
    mdiFolder,
    mdiFolderOutline,
    mdiFolderStar,
    mdiFolderStarOutline,
    mdiArchive,
    mdiArchiveOutline,
    mdiPackage,
    mdiPackageVariant,
    mdiPackageVariantClosed,
    mdiGift,
    mdiGiftOutline,
    mdiCart,
    mdiCartOutline,
    mdiCartOff,
    mdiBasket,
    mdiBasketOutline,
    mdiBasketFill,
    mdiDiamond,
    mdiDiamondOutline,
    mdiCrystalBall,
    mdiSphere,
    mdiCube,
    mdiCubeOutline,
    mdiCubeSend,
    mdiCubeUnfolded,
    mdiBox,
    mdiBriefcase,
    mdiBriefcaseOutline,
    mdiBriefcaseVariant,
    mdiBriefcaseVariantOutline,
    mdiWallet,
    mdiWalletOutline,
    mdiCash,
    mdiCashMultiple,
    mdiCurrencyUsd,
    mdiTreasureChest,
    mdiTreasureChestOutline,
    mdiRocket,
    mdiRocketOutline,
    mdiRocketLaunch,
    mdiRocketLaunchOutline,
    mdiSpaceStation,
    mdiSatellite,
    mdiSatelliteVariant,
    mdiOrbit,
    mdiEarth,
    mdiMoonFull,
    mdiWeatherNight,
    mdiWeatherSunny,
    mdiWeatherLightning,
    mdiWeatherSnowy,
    mdiWeatherWindy,
    mdiWeatherHurricane,
    mdiCloud,
    mdiCloudOutline,
    mdiCloudUpload,
    mdiCloudUploadOutline,
    mdiCloudDownload,
    mdiCloudDownloadOutline,
    mdiCloudSync,
    mdiCloudSyncOutline,
    mdiWater,
    mdiWaterOutline,
    mdiWaterPump,
    mdiWaterPumpOff,
    mdiWaterPercent,
    mdiWaterPercentAlert,
    mdiWaterOff,
    mdiWaterOffOutline,
    mdiWaterSync,
    mdiFireplace,
    mdiFireplaceOff,
    mdiCampfire,
    mdiCandle,
    mdiLightbulb,
    mdiLightbulbOutline,
    mdiLightbulbOn,
    mdiLightbulbOnOutline,
    mdiFlash,
    mdiFlashOutline,
    mdiBattery,
    mdiBatteryCharging,
    mdiBatteryLow,
    mdiBatteryAlert,
    mdiPower,
    mdiPowerPlug,
    mdiPowerPlugOutline,
    mdiPowerSocket,
    mdiConnection,
    mdiLink,
    mdiLinkVariant,
    mdiLinkVariantOff,
    mdiLinkPlus,
    mdiLinkLock,
    mdiAnchor,
    mdiCompass,
    mdiCompassOutline,
    mdiMap,
    mdiMapOutline,
    mdiMapMarker,
    mdiMapMarkerOutline,
    mdiMapMarkerRadius,
    mdiMapMarkerRadiusOutline,
    mdiFlag,
    mdiFlagOutline,
    mdiFlagVariant,
    mdiFlagVariantOutline,
    mdiFlagCheckered,
    mdiFlagTriangle,
    mdiFlagRemove,
    mdiFlagRemoveOutline,
    mdiHeart,
    mdiHeartOutline,
    mdiHeartPulse,
    mdiHeartHalf,
    mdiHeartHalfOutline,
    mdiHeartHalfFull,
    mdiHandClap,
    mdiHandPeace,
    mdiHandOkay,
    mdiHandSaw,
    mdiHandshake,
    mdiAccount,
    mdiAccountOutline,
    mdiAccountStar,
    mdiAccountStarOutline,
    mdiAccountCheck,
    mdiAccountCheckOutline,
    mdiAccountAlert,
    mdiAccountAlertOutline,
    mdiAccountGroup,
    mdiAccountGroupOutline,
    mdiAccountMultiple,
    mdiAccountMultipleOutline,
    mdiAccountMultiplePlus,
    mdiAccountMultiplePlusOutline,
    mdiAccountPlus,
    mdiAccountPlusOutline,
    mdiAccountMinus,
    mdiAccountMinusOutline,
    mdiAccountRemove,
    mdiAccountRemoveOutline,
    mdiAccountSettings,
    mdiAccountSettingsOutline,
    mdiAccountTie,
    mdiAccountTieOutline,
    mdiAccountCowboyHat,
    mdiAccountCowboyHatOutline,
    mdiAccountTieHat,
    mdiAccountTieHatOutline,
    mdiFaceMan,
    mdiFaceManOutline,
    mdiFaceWoman,
    mdiFaceWomanOutline,
    mdiFaceManProfile,
    mdiFaceWomanProfile,
    mdiHead,
    mdiHeadOutline,
    mdiBrain,
    mdiEye,
    mdiEyeOutline,
    mdiEyeOff,
    mdiEyeOffOutline,
    mdiEyeCheck,
    mdiEyeCheckOutline,
    mdiEyeSettings,
    mdiEyeSettingsOutline,
    mdiEarHearing,
    mdiEarHearingOff,
    mdiChiliHot,
    mdiChiliMedium,
    mdiChiliMild,
    mdiFood,
    mdiFoodOutline,
    mdiFoodApple,
    mdiFoodAppleOutline,
    mdiFoodVariant,
    mdiFoodVariantOff,
    mdiFoodDrumstick,
    mdiFoodDrumstickOutline,
    mdiFoodSteak,
    mdiFoodSteakOff,
    mdiFoodHotDog,
    mdiHamburger,
    mdiPizza,
    mdiFoodTakeoutBox,
    mdiFoodTakeoutBoxOutline,
    mdiCup,
    mdiCupOutline,
    mdiCupOff,
    mdiCupOffOutline,
    mdiCupWater,
    mdiGlassMug,
    mdiGlassMugVariant,
    mdiGlassCocktail,
    mdiGlassWine,
    mdiGlassPintOutline,
    mdiBeer,
    mdiBeerOutline,
    mdiCoffee,
    mdiCoffeeOutline,
    mdiTea,
    mdiTeaOutline,
    mdiKettle,
    mdiKettleOutline,
    mdiPot,
    mdiPotOutline,
    mdiPotSteam,
    mdiPotSteamOutline,
    mdiPan,
    mdiPanTopLeft,
    mdiPanBottomLeft,
    mdiPanBottomRight,
    mdiBowl,
    mdiBowlOutline,
    mdiBowlMix,
    mdiBowlMixOutline,
    mdiSilverware,
    mdiSilverwareFork,
    mdiSilverwareSpoon,
    mdiSilverwareVariant,
    mdiSilverwareClean,
    mdiSilverwareForkKnife,
    mdiKnife,
    mdiKnifeMilitary,
    mdiDishwasher,
    mdiMicrowave,
    mdiStove,
    mdiFridge,
    mdiFridgeVariant,
    mdiWashingMachine,
    mdiTumbleDryer,
    mdiToaster,
    mdiBlender,
    mdiBlenderSoftware,
    mdiThermometer,
    mdiThermometerHigh,
    mdiThermometerLow,
    mdiThermometerAlert,
    mdiThermometerChevronUp,
    mdiThermometerChevronDown,
    mdiThermometerMinus,
    mdiThermometerPlus,
    mdiThermometerLines,
    mdiThermometerWater,
    mdiThermometerProbe,
    mdiThermometerProbeOff,
    mdiWaterBoiler,
    mdiWaterBoilerAlert,
    mdiWaterBoilerOff,
    mdiWaterAlert,
    mdiWaterCheck,
    mdiWaterMinus,
    mdiWaterPlus,
    mdiWaterRemove,
    mdiWaterCircle,
    mdiWaterPolo,
    mdiBottleSoda,
    mdiBottleSodaOutline,
    mdiBottleWine,
    mdiBottleTonic,
    mdiBottleTonicOutline,
    mdiBottleTonicPlus,
    mdiBottleTonicPlusOutline,
    mdiBottleTonicSkull,
    mdiBottleTonicSkullOutline
} from '@mdi/js';

export const rankIconOptions = [
    { value: '', label: 'No icon', path: '' },
    { value: "trophy", label: "Trophy", path: mdiTrophy },
    { value: "trophy-award", label: "Trophy Award", path: mdiTrophyAward },
    { value: "trophy-variant", label: "Trophy Variant", path: mdiTrophyVariant },
    { value: "medal", label: "Medal", path: mdiMedal },
    { value: "medal-outline", label: "Medal Outline", path: mdiMedalOutline },
    { value: "crown", label: "Crown", path: mdiCrown },
    { value: "crown-outline", label: "Crown Outline", path: mdiCrownOutline },
    { value: "star", label: "Star", path: mdiStar },
    { value: "star-outline", label: "Star Outline", path: mdiStarOutline },
    { value: "star-four-points", label: "Star Four Points", path: mdiStarFourPoints },
    { value: "star-three-points", label: "Star Three Points", path: mdiStarThreePoints },
    { value: "star-circle", label: "Star Circle", path: mdiStarCircle },
    { value: "star-face", label: "Star Face", path: mdiStarFace },
    { value: "emoticon-happy", label: "Emoticon Happy", path: mdiEmoticonHappy },
    { value: "emoticon-cool", label: "Emoticon Cool", path: mdiEmoticonCool },
    { value: "emoticon-devil", label: "Emoticon Devil", path: mdiEmoticonDevil },
    { value: "emoticon-excited", label: "Emoticon Excited", path: mdiEmoticonExcited },
    { value: "fire", label: "Fire", path: mdiFire },
    { value: "lightning-bolt", label: "Lightning Bolt", path: mdiLightningBolt },
    { value: "lightning-bolt-circle", label: "Lightning Bolt Circle", path: mdiLightningBoltCircle },
    { value: "shield", label: "Shield", path: mdiShield },
    { value: "shield-outline", label: "Shield Outline", path: mdiShieldOutline },
    { value: "shield-check", label: "Shield Check", path: mdiShieldCheck },
    { value: "shield-check-outline", label: "Shield Check Outline", path: mdiShieldCheckOutline },
    { value: "shield-alert", label: "Shield Alert", path: mdiShieldAlert },
    { value: "shield-alert-outline", label: "Shield Alert Outline", path: mdiShieldAlertOutline },
    { value: "shield-star", label: "Shield Star", path: mdiShieldStar },
    { value: "shield-star-outline", label: "Shield Star Outline", path: mdiShieldStarOutline },
    { value: "shield-lock", label: "Shield Lock", path: mdiShieldLock },
    { value: "shield-lock-outline", label: "Shield Lock Outline", path: mdiShieldLockOutline },
    { value: "sword", label: "Sword", path: mdiSword },
    { value: "sword-cross", label: "Sword Cross", path: mdiSwordCross },
    { value: "axe", label: "Axe", path: mdiAxe },
    { value: "axe-battle", label: "Axe Battle", path: mdiAxeBattle },
    { value: "mace", label: "Mace", path: mdiMace },
    { value: "hammer", label: "Hammer", path: mdiHammer },
    { value: "hammer-screwdriver", label: "Hammer Screwdriver", path: mdiHammerScrewdriver },
    { value: "hammer-wrench", label: "Hammer Wrench", path: mdiHammerWrench },
    { value: "wrench", label: "Wrench", path: mdiWrench },
    { value: "wrench-clock", label: "Wrench Clock", path: mdiWrenchClock },
    { value: "cog", label: "Cog", path: mdiCog },
    { value: "cog-outline", label: "Cog Outline", path: mdiCogOutline },
    { value: "cog-play", label: "Cog Play", path: mdiCogPlay },
    { value: "cog-play-outline", label: "Cog Play Outline", path: mdiCogPlayOutline },
    { value: "cog-box", label: "Cog Box", path: mdiCogBox },
    { value: "tools", label: "Tools", path: mdiTools },
    { value: "screwdriver", label: "Screwdriver", path: mdiScrewdriver },
    { value: "pliers", label: "Pliers", path: mdiPliers },
    { value: "pencil", label: "Pencil", path: mdiPencil },
    { value: "pencil-outline", label: "Pencil Outline", path: mdiPencilOutline },
    { value: "pencil-ruler", label: "Pencil Ruler", path: mdiPencilRuler },
    { value: "pen", label: "Pen", path: mdiPen },
    { value: "brush", label: "Brush", path: mdiBrush },
    { value: "palette", label: "Palette", path: mdiPalette },
    { value: "palette-outline", label: "Palette Outline", path: mdiPaletteOutline },
    { value: "format-paint", label: "Format Paint", path: mdiFormatPaint },
    { value: "code-braces", label: "Code Braces", path: mdiCodeBraces },
    { value: "code-braces-box", label: "Code Braces Box", path: mdiCodeBracesBox },
    { value: "code-tags", label: "Code Tags", path: mdiCodeTags },
    { value: "console", label: "Console", path: mdiConsole },
    { value: "monitor", label: "Monitor", path: mdiMonitor },
    { value: "monitor-cellphone", label: "Monitor Cellphone", path: mdiMonitorCellphone },
    { value: "laptop", label: "Laptop", path: mdiLaptop },
    { value: "cellphone", label: "Cellphone", path: mdiCellphone },
    { value: "tablet", label: "Tablet", path: mdiTablet },
    { value: "server", label: "Server", path: mdiServer },
    { value: "database", label: "Database", path: mdiDatabase },
    { value: "database-outline", label: "Database Outline", path: mdiDatabaseOutline },
    { value: "harddisk", label: "Harddisk", path: mdiHarddisk },
    { value: "memory", label: "Memory", path: mdiMemory },
    { value: "chip", label: "Chip", path: mdiChip },
    { value: "cpu64-bit", label: "Cpu64 Bit", path: mdiCpu64Bit },
    { value: "cpu32-bit", label: "Cpu32 Bit", path: mdiCpu32Bit },
    { value: "video", label: "Video", path: mdiVideo },
    { value: "video-outline", label: "Video Outline", path: mdiVideoOutline },
    { value: "camera", label: "Camera", path: mdiCamera },
    { value: "camera-outline", label: "Camera Outline", path: mdiCameraOutline },
    { value: "image", label: "Image", path: mdiImage },
    { value: "image-outline", label: "Image Outline", path: mdiImageOutline },
    { value: "file", label: "File", path: mdiFile },
    { value: "file-outline", label: "File Outline", path: mdiFileOutline },
    { value: "file-document", label: "File Document", path: mdiFileDocument },
    { value: "file-document-outline", label: "File Document Outline", path: mdiFileDocumentOutline },
    { value: "file-code", label: "File Code", path: mdiFileCode },
    { value: "file-code-outline", label: "File Code Outline", path: mdiFileCodeOutline },
    { value: "folder", label: "Folder", path: mdiFolder },
    { value: "folder-outline", label: "Folder Outline", path: mdiFolderOutline },
    { value: "folder-star", label: "Folder Star", path: mdiFolderStar },
    { value: "folder-star-outline", label: "Folder Star Outline", path: mdiFolderStarOutline },
    { value: "archive", label: "Archive", path: mdiArchive },
    { value: "archive-outline", label: "Archive Outline", path: mdiArchiveOutline },
    { value: "package", label: "Package", path: mdiPackage },
    { value: "package-variant", label: "Package Variant", path: mdiPackageVariant },
    { value: "package-variant-closed", label: "Package Variant Closed", path: mdiPackageVariantClosed },
    { value: "gift", label: "Gift", path: mdiGift },
    { value: "gift-outline", label: "Gift Outline", path: mdiGiftOutline },
    { value: "cart", label: "Cart", path: mdiCart },
    { value: "cart-outline", label: "Cart Outline", path: mdiCartOutline },
    { value: "cart-off", label: "Cart Off", path: mdiCartOff },
    { value: "basket", label: "Basket", path: mdiBasket },
    { value: "basket-outline", label: "Basket Outline", path: mdiBasketOutline },
    { value: "basket-fill", label: "Basket Fill", path: mdiBasketFill },
    { value: "diamond", label: "Diamond", path: mdiDiamond },
    { value: "diamond-outline", label: "Diamond Outline", path: mdiDiamondOutline },
    { value: "crystal-ball", label: "Crystal Ball", path: mdiCrystalBall },
    { value: "sphere", label: "Sphere", path: mdiSphere },
    { value: "cube", label: "Cube", path: mdiCube },
    { value: "cube-outline", label: "Cube Outline", path: mdiCubeOutline },
    { value: "cube-send", label: "Cube Send", path: mdiCubeSend },
    { value: "cube-unfolded", label: "Cube Unfolded", path: mdiCubeUnfolded },
    { value: "box", label: "Box", path: mdiBox },
    { value: "briefcase", label: "Briefcase", path: mdiBriefcase },
    { value: "briefcase-outline", label: "Briefcase Outline", path: mdiBriefcaseOutline },
    { value: "briefcase-variant", label: "Briefcase Variant", path: mdiBriefcaseVariant },
    { value: "briefcase-variant-outline", label: "Briefcase Variant Outline", path: mdiBriefcaseVariantOutline },
    { value: "wallet", label: "Wallet", path: mdiWallet },
    { value: "wallet-outline", label: "Wallet Outline", path: mdiWalletOutline },
    { value: "cash", label: "Cash", path: mdiCash },
    { value: "cash-multiple", label: "Cash Multiple", path: mdiCashMultiple },
    { value: "currency-usd", label: "Currency Usd", path: mdiCurrencyUsd },
    { value: "treasure-chest", label: "Treasure Chest", path: mdiTreasureChest },
    { value: "treasure-chest-outline", label: "Treasure Chest Outline", path: mdiTreasureChestOutline },
    { value: "rocket", label: "Rocket", path: mdiRocket },
    { value: "rocket-outline", label: "Rocket Outline", path: mdiRocketOutline },
    { value: "rocket-launch", label: "Rocket Launch", path: mdiRocketLaunch },
    { value: "rocket-launch-outline", label: "Rocket Launch Outline", path: mdiRocketLaunchOutline },
    { value: "space-station", label: "Space Station", path: mdiSpaceStation },
    { value: "satellite", label: "Satellite", path: mdiSatellite },
    { value: "satellite-variant", label: "Satellite Variant", path: mdiSatelliteVariant },
    { value: "orbit", label: "Orbit", path: mdiOrbit },
    { value: "earth", label: "Earth", path: mdiEarth },
    { value: "moon-full", label: "Moon Full", path: mdiMoonFull },
    { value: "weather-night", label: "Weather Night", path: mdiWeatherNight },
    { value: "weather-sunny", label: "Weather Sunny", path: mdiWeatherSunny },
    { value: "weather-lightning", label: "Weather Lightning", path: mdiWeatherLightning },
    { value: "weather-snowy", label: "Weather Snowy", path: mdiWeatherSnowy },
    { value: "weather-windy", label: "Weather Windy", path: mdiWeatherWindy },
    { value: "weather-hurricane", label: "Weather Hurricane", path: mdiWeatherHurricane },
    { value: "cloud", label: "Cloud", path: mdiCloud },
    { value: "cloud-outline", label: "Cloud Outline", path: mdiCloudOutline },
    { value: "cloud-upload", label: "Cloud Upload", path: mdiCloudUpload },
    { value: "cloud-upload-outline", label: "Cloud Upload Outline", path: mdiCloudUploadOutline },
    { value: "cloud-download", label: "Cloud Download", path: mdiCloudDownload },
    { value: "cloud-download-outline", label: "Cloud Download Outline", path: mdiCloudDownloadOutline },
    { value: "cloud-sync", label: "Cloud Sync", path: mdiCloudSync },
    { value: "cloud-sync-outline", label: "Cloud Sync Outline", path: mdiCloudSyncOutline },
    { value: "water", label: "Water", path: mdiWater },
    { value: "water-outline", label: "Water Outline", path: mdiWaterOutline },
    { value: "water-pump", label: "Water Pump", path: mdiWaterPump },
    { value: "water-pump-off", label: "Water Pump Off", path: mdiWaterPumpOff },
    { value: "water-percent", label: "Water Percent", path: mdiWaterPercent },
    { value: "water-percent-alert", label: "Water Percent Alert", path: mdiWaterPercentAlert },
    { value: "water-off", label: "Water Off", path: mdiWaterOff },
    { value: "water-off-outline", label: "Water Off Outline", path: mdiWaterOffOutline },
    { value: "water-sync", label: "Water Sync", path: mdiWaterSync },
    { value: "fireplace", label: "Fireplace", path: mdiFireplace },
    { value: "fireplace-off", label: "Fireplace Off", path: mdiFireplaceOff },
    { value: "campfire", label: "Campfire", path: mdiCampfire },
    { value: "candle", label: "Candle", path: mdiCandle },
    { value: "lightbulb", label: "Lightbulb", path: mdiLightbulb },
    { value: "lightbulb-outline", label: "Lightbulb Outline", path: mdiLightbulbOutline },
    { value: "lightbulb-on", label: "Lightbulb On", path: mdiLightbulbOn },
    { value: "lightbulb-on-outline", label: "Lightbulb On Outline", path: mdiLightbulbOnOutline },
    { value: "flash", label: "Flash", path: mdiFlash },
    { value: "flash-outline", label: "Flash Outline", path: mdiFlashOutline },
    { value: "battery", label: "Battery", path: mdiBattery },
    { value: "battery-charging", label: "Battery Charging", path: mdiBatteryCharging },
    { value: "battery-low", label: "Battery Low", path: mdiBatteryLow },
    { value: "battery-alert", label: "Battery Alert", path: mdiBatteryAlert },
    { value: "power", label: "Power", path: mdiPower },
    { value: "power-plug", label: "Power Plug", path: mdiPowerPlug },
    { value: "power-plug-outline", label: "Power Plug Outline", path: mdiPowerPlugOutline },
    { value: "power-socket", label: "Power Socket", path: mdiPowerSocket },
    { value: "connection", label: "Connection", path: mdiConnection },
    { value: "link", label: "Link", path: mdiLink },
    { value: "link-variant", label: "Link Variant", path: mdiLinkVariant },
    { value: "link-variant-off", label: "Link Variant Off", path: mdiLinkVariantOff },
    { value: "link-plus", label: "Link Plus", path: mdiLinkPlus },
    { value: "link-lock", label: "Link Lock", path: mdiLinkLock },
    { value: "anchor", label: "Anchor", path: mdiAnchor },
    { value: "compass", label: "Compass", path: mdiCompass },
    { value: "compass-outline", label: "Compass Outline", path: mdiCompassOutline },
    { value: "map", label: "Map", path: mdiMap },
    { value: "map-outline", label: "Map Outline", path: mdiMapOutline },
    { value: "map-marker", label: "Map Marker", path: mdiMapMarker },
    { value: "map-marker-outline", label: "Map Marker Outline", path: mdiMapMarkerOutline },
    { value: "map-marker-radius", label: "Map Marker Radius", path: mdiMapMarkerRadius },
    { value: "map-marker-radius-outline", label: "Map Marker Radius Outline", path: mdiMapMarkerRadiusOutline },
    { value: "flag", label: "Flag", path: mdiFlag },
    { value: "flag-outline", label: "Flag Outline", path: mdiFlagOutline },
    { value: "flag-variant", label: "Flag Variant", path: mdiFlagVariant },
    { value: "flag-variant-outline", label: "Flag Variant Outline", path: mdiFlagVariantOutline },
    { value: "flag-checkered", label: "Flag Checkered", path: mdiFlagCheckered },
    { value: "flag-triangle", label: "Flag Triangle", path: mdiFlagTriangle },
    { value: "flag-remove", label: "Flag Remove", path: mdiFlagRemove },
    { value: "flag-remove-outline", label: "Flag Remove Outline", path: mdiFlagRemoveOutline },
    { value: "heart", label: "Heart", path: mdiHeart },
    { value: "heart-outline", label: "Heart Outline", path: mdiHeartOutline },
    { value: "heart-pulse", label: "Heart Pulse", path: mdiHeartPulse },
    { value: "heart-half", label: "Heart Half", path: mdiHeartHalf },
    { value: "heart-half-outline", label: "Heart Half Outline", path: mdiHeartHalfOutline },
    { value: "heart-half-full", label: "Heart Half Full", path: mdiHeartHalfFull },
    { value: "hand-clap", label: "Hand Clap", path: mdiHandClap },
    { value: "hand-peace", label: "Hand Peace", path: mdiHandPeace },
    { value: "hand-okay", label: "Hand Okay", path: mdiHandOkay },
    { value: "hand-saw", label: "Hand Saw", path: mdiHandSaw },
    { value: "handshake", label: "Handshake", path: mdiHandshake },
    { value: "account", label: "Account", path: mdiAccount },
    { value: "account-outline", label: "Account Outline", path: mdiAccountOutline },
    { value: "account-star", label: "Account Star", path: mdiAccountStar },
    { value: "account-star-outline", label: "Account Star Outline", path: mdiAccountStarOutline },
    { value: "account-check", label: "Account Check", path: mdiAccountCheck },
    { value: "account-check-outline", label: "Account Check Outline", path: mdiAccountCheckOutline },
    { value: "account-alert", label: "Account Alert", path: mdiAccountAlert },
    { value: "account-alert-outline", label: "Account Alert Outline", path: mdiAccountAlertOutline },
    { value: "account-group", label: "Account Group", path: mdiAccountGroup },
    { value: "account-group-outline", label: "Account Group Outline", path: mdiAccountGroupOutline },
    { value: "account-multiple", label: "Account Multiple", path: mdiAccountMultiple },
    { value: "account-multiple-outline", label: "Account Multiple Outline", path: mdiAccountMultipleOutline },
    { value: "account-multiple-plus", label: "Account Multiple Plus", path: mdiAccountMultiplePlus },
    { value: "account-multiple-plus-outline", label: "Account Multiple Plus Outline", path: mdiAccountMultiplePlusOutline },
    { value: "account-plus", label: "Account Plus", path: mdiAccountPlus },
    { value: "account-plus-outline", label: "Account Plus Outline", path: mdiAccountPlusOutline },
    { value: "account-minus", label: "Account Minus", path: mdiAccountMinus },
    { value: "account-minus-outline", label: "Account Minus Outline", path: mdiAccountMinusOutline },
    { value: "account-remove", label: "Account Remove", path: mdiAccountRemove },
    { value: "account-remove-outline", label: "Account Remove Outline", path: mdiAccountRemoveOutline },
    { value: "account-settings", label: "Account Settings", path: mdiAccountSettings },
    { value: "account-settings-outline", label: "Account Settings Outline", path: mdiAccountSettingsOutline },
    { value: "account-tie", label: "Account Tie", path: mdiAccountTie },
    { value: "account-tie-outline", label: "Account Tie Outline", path: mdiAccountTieOutline },
    { value: "account-cowboy-hat", label: "Account Cowboy Hat", path: mdiAccountCowboyHat },
    { value: "account-cowboy-hat-outline", label: "Account Cowboy Hat Outline", path: mdiAccountCowboyHatOutline },
    { value: "account-tie-hat", label: "Account Tie Hat", path: mdiAccountTieHat },
    { value: "account-tie-hat-outline", label: "Account Tie Hat Outline", path: mdiAccountTieHatOutline },
    { value: "face-man", label: "Face Man", path: mdiFaceMan },
    { value: "face-man-outline", label: "Face Man Outline", path: mdiFaceManOutline },
    { value: "face-woman", label: "Face Woman", path: mdiFaceWoman },
    { value: "face-woman-outline", label: "Face Woman Outline", path: mdiFaceWomanOutline },
    { value: "face-man-profile", label: "Face Man Profile", path: mdiFaceManProfile },
    { value: "face-woman-profile", label: "Face Woman Profile", path: mdiFaceWomanProfile },
    { value: "head", label: "Head", path: mdiHead },
    { value: "head-outline", label: "Head Outline", path: mdiHeadOutline },
    { value: "brain", label: "Brain", path: mdiBrain },
    { value: "eye", label: "Eye", path: mdiEye },
    { value: "eye-outline", label: "Eye Outline", path: mdiEyeOutline },
    { value: "eye-off", label: "Eye Off", path: mdiEyeOff },
    { value: "eye-off-outline", label: "Eye Off Outline", path: mdiEyeOffOutline },
    { value: "eye-check", label: "Eye Check", path: mdiEyeCheck },
    { value: "eye-check-outline", label: "Eye Check Outline", path: mdiEyeCheckOutline },
    { value: "eye-settings", label: "Eye Settings", path: mdiEyeSettings },
    { value: "eye-settings-outline", label: "Eye Settings Outline", path: mdiEyeSettingsOutline },
    { value: "ear-hearing", label: "Ear Hearing", path: mdiEarHearing },
    { value: "ear-hearing-off", label: "Ear Hearing Off", path: mdiEarHearingOff },
    { value: "chili-hot", label: "Chili Hot", path: mdiChiliHot },
    { value: "chili-medium", label: "Chili Medium", path: mdiChiliMedium },
    { value: "chili-mild", label: "Chili Mild", path: mdiChiliMild },
    { value: "food", label: "Food", path: mdiFood },
    { value: "food-outline", label: "Food Outline", path: mdiFoodOutline },
    { value: "food-apple", label: "Food Apple", path: mdiFoodApple },
    { value: "food-apple-outline", label: "Food Apple Outline", path: mdiFoodAppleOutline },
    { value: "food-variant", label: "Food Variant", path: mdiFoodVariant },
    { value: "food-variant-off", label: "Food Variant Off", path: mdiFoodVariantOff },
    { value: "food-drumstick", label: "Food Drumstick", path: mdiFoodDrumstick },
    { value: "food-drumstick-outline", label: "Food Drumstick Outline", path: mdiFoodDrumstickOutline },
    { value: "food-steak", label: "Food Steak", path: mdiFoodSteak },
    { value: "food-steak-off", label: "Food Steak Off", path: mdiFoodSteakOff },
    { value: "food-hot-dog", label: "Food Hot Dog", path: mdiFoodHotDog },
    { value: "hamburger", label: "Hamburger", path: mdiHamburger },
    { value: "pizza", label: "Pizza", path: mdiPizza },
    { value: "food-takeout-box", label: "Food Takeout Box", path: mdiFoodTakeoutBox },
    { value: "food-takeout-box-outline", label: "Food Takeout Box Outline", path: mdiFoodTakeoutBoxOutline },
    { value: "cup", label: "Cup", path: mdiCup },
    { value: "cup-outline", label: "Cup Outline", path: mdiCupOutline },
    { value: "cup-off", label: "Cup Off", path: mdiCupOff },
    { value: "cup-off-outline", label: "Cup Off Outline", path: mdiCupOffOutline },
    { value: "cup-water", label: "Cup Water", path: mdiCupWater },
    { value: "glass-mug", label: "Glass Mug", path: mdiGlassMug },
    { value: "glass-mug-variant", label: "Glass Mug Variant", path: mdiGlassMugVariant },
    { value: "glass-cocktail", label: "Glass Cocktail", path: mdiGlassCocktail },
    { value: "glass-wine", label: "Glass Wine", path: mdiGlassWine },
    { value: "glass-pint-outline", label: "Glass Pint Outline", path: mdiGlassPintOutline },
    { value: "beer", label: "Beer", path: mdiBeer },
    { value: "beer-outline", label: "Beer Outline", path: mdiBeerOutline },
    { value: "coffee", label: "Coffee", path: mdiCoffee },
    { value: "coffee-outline", label: "Coffee Outline", path: mdiCoffeeOutline },
    { value: "tea", label: "Tea", path: mdiTea },
    { value: "tea-outline", label: "Tea Outline", path: mdiTeaOutline },
    { value: "kettle", label: "Kettle", path: mdiKettle },
    { value: "kettle-outline", label: "Kettle Outline", path: mdiKettleOutline },
    { value: "pot", label: "Pot", path: mdiPot },
    { value: "pot-outline", label: "Pot Outline", path: mdiPotOutline },
    { value: "pot-steam", label: "Pot Steam", path: mdiPotSteam },
    { value: "pot-steam-outline", label: "Pot Steam Outline", path: mdiPotSteamOutline },
    { value: "pan", label: "Pan", path: mdiPan },
    { value: "pan-top-left", label: "Pan Top Left", path: mdiPanTopLeft },
    { value: "pan-bottom-left", label: "Pan Bottom Left", path: mdiPanBottomLeft },
    { value: "pan-bottom-right", label: "Pan Bottom Right", path: mdiPanBottomRight },
    { value: "bowl", label: "Bowl", path: mdiBowl },
    { value: "bowl-outline", label: "Bowl Outline", path: mdiBowlOutline },
    { value: "bowl-mix", label: "Bowl Mix", path: mdiBowlMix },
    { value: "bowl-mix-outline", label: "Bowl Mix Outline", path: mdiBowlMixOutline },
    { value: "silverware", label: "Silverware", path: mdiSilverware },
    { value: "silverware-fork", label: "Silverware Fork", path: mdiSilverwareFork },
    { value: "silverware-spoon", label: "Silverware Spoon", path: mdiSilverwareSpoon },
    { value: "silverware-variant", label: "Silverware Variant", path: mdiSilverwareVariant },
    { value: "silverware-clean", label: "Silverware Clean", path: mdiSilverwareClean },
    { value: "silverware-fork-knife", label: "Silverware Fork Knife", path: mdiSilverwareForkKnife },
    { value: "knife", label: "Knife", path: mdiKnife },
    { value: "knife-military", label: "Knife Military", path: mdiKnifeMilitary },
    { value: "dishwasher", label: "Dishwasher", path: mdiDishwasher },
    { value: "microwave", label: "Microwave", path: mdiMicrowave },
    { value: "stove", label: "Stove", path: mdiStove },
    { value: "fridge", label: "Fridge", path: mdiFridge },
    { value: "fridge-variant", label: "Fridge Variant", path: mdiFridgeVariant },
    { value: "washing-machine", label: "Washing Machine", path: mdiWashingMachine },
    { value: "tumble-dryer", label: "Tumble Dryer", path: mdiTumbleDryer },
    { value: "toaster", label: "Toaster", path: mdiToaster },
    { value: "blender", label: "Blender", path: mdiBlender },
    { value: "blender-software", label: "Blender Software", path: mdiBlenderSoftware },
    { value: "thermometer", label: "Thermometer", path: mdiThermometer },
    { value: "thermometer-high", label: "Thermometer High", path: mdiThermometerHigh },
    { value: "thermometer-low", label: "Thermometer Low", path: mdiThermometerLow },
    { value: "thermometer-alert", label: "Thermometer Alert", path: mdiThermometerAlert },
    { value: "thermometer-chevron-up", label: "Thermometer Chevron Up", path: mdiThermometerChevronUp },
    { value: "thermometer-chevron-down", label: "Thermometer Chevron Down", path: mdiThermometerChevronDown },
    { value: "thermometer-minus", label: "Thermometer Minus", path: mdiThermometerMinus },
    { value: "thermometer-plus", label: "Thermometer Plus", path: mdiThermometerPlus },
    { value: "thermometer-lines", label: "Thermometer Lines", path: mdiThermometerLines },
    { value: "thermometer-water", label: "Thermometer Water", path: mdiThermometerWater },
    { value: "thermometer-probe", label: "Thermometer Probe", path: mdiThermometerProbe },
    { value: "thermometer-probe-off", label: "Thermometer Probe Off", path: mdiThermometerProbeOff },
    { value: "water-boiler", label: "Water Boiler", path: mdiWaterBoiler },
    { value: "water-boiler-alert", label: "Water Boiler Alert", path: mdiWaterBoilerAlert },
    { value: "water-boiler-off", label: "Water Boiler Off", path: mdiWaterBoilerOff },
    { value: "water-alert", label: "Water Alert", path: mdiWaterAlert },
    { value: "water-check", label: "Water Check", path: mdiWaterCheck },
    { value: "water-minus", label: "Water Minus", path: mdiWaterMinus },
    { value: "water-plus", label: "Water Plus", path: mdiWaterPlus },
    { value: "water-remove", label: "Water Remove", path: mdiWaterRemove },
    { value: "water-circle", label: "Water Circle", path: mdiWaterCircle },
    { value: "water-polo", label: "Water Polo", path: mdiWaterPolo },
    { value: "bottle-soda", label: "Bottle Soda", path: mdiBottleSoda },
    { value: "bottle-soda-outline", label: "Bottle Soda Outline", path: mdiBottleSodaOutline },
    { value: "bottle-wine", label: "Bottle Wine", path: mdiBottleWine },
    { value: "bottle-tonic", label: "Bottle Tonic", path: mdiBottleTonic },
    { value: "bottle-tonic-outline", label: "Bottle Tonic Outline", path: mdiBottleTonicOutline },
    { value: "bottle-tonic-plus", label: "Bottle Tonic Plus", path: mdiBottleTonicPlus },
    { value: "bottle-tonic-plus-outline", label: "Bottle Tonic Plus Outline", path: mdiBottleTonicPlusOutline },
    { value: "bottle-tonic-skull", label: "Bottle Tonic Skull", path: mdiBottleTonicSkull },
    { value: "bottle-tonic-skull-outline", label: "Bottle Tonic Skull Outline", path: mdiBottleTonicSkullOutline }
];

interface RankIconProps {
    value: string | null;
    className?: string;
}

export default function RankIcon({ value, className = '' }: RankIconProps) {
    const option = rankIconOptions.find((o) => o.value === value);

    if (!option?.path) {
        return null;
    }

    return <Icon path={option.path} size={1} className={className} />;
}

